<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components" Version="6.0.6" />
    </ItemGroup>

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Assets\app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
      <ProjectReference Include="..\TetrisEngine\TetrisEngine.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <None Update="TetrisMenuButton.xaml">
        <Generator>MSBuild:Compile</Generator>
      </None>
    </ItemGroup>

</Project>
